package Commands;

import static HelperPackage.HelperFunctions.*;
import static HelperPackage.SendingFunctions.*;

import java.util.Arrays;
import java.util.List;

import static HelperPackage.GlobalVars.*;

import net.dv8tion.jda.core.entities.Emote;
import net.dv8tion.jda.core.events.message.MessageReceivedEvent;

public class ReactionCommands {
	/*
	 * BE COOL
	 */
	public static void becool(MessageReceivedEvent event, String call) {
		sendMsg(event.getChannel(), ":sunglasses:");
	}
	
	/*
	 * BE ANGERY
	 */
	public static void beangery(MessageReceivedEvent event, String call) {
		sendMsg(event.getChannel(), ":rage:");
	}

	/*
	 * LAUGH
	 */
	public static void laugh(MessageReceivedEvent event, String call) {
		sendMsg(event.getChannel(), ":joy:");
	}
	
	/*
	 * CRY
	 */
	public static void cry(MessageReceivedEvent event, String call) {
		sendMsg(event.getChannel(), ":sob:");
	}
	
	/*
	 * BE A NORMIE
	 */
	private static List<String> normieEmotes = Arrays.asList(":joy:",
															 ":100:",
															 ":ok_hand:",
															 ":heart_eyes:");
	public static void beanormie(MessageReceivedEvent event, String call) {
		String msg = "";
		int amount = randomInt(5, 15);
		for (int i = 0; i < amount; i++) {
			msg += normieEmotes.get(randomInt(0, normieEmotes.size() - 1));
		}
		sendMsg(event.getChannel(), msg);
	}
	
	/*
	 * SAY
	 */
	public static void say(MessageReceivedEvent event, String call) {
		if (call.equals("")) { return; }
		call = convertMentions(event).replaceFirst(prefix + "say", "").trim();
		for (Emote e : event.getMessage().getEmotes()) {
			call = call.replace(':' + e.getName() + ':', e.getAsMention());
			
		}
		sendMsg(event.getChannel(), call);
	}
	
	/*
	 * REEE
	 */
	public static void reee(MessageReceivedEvent event, String call) {
		sendMsg(event.getChannel(), "REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE");
	}
	
	/*
	 * WRIST
	 */
	public static void slashwrist(MessageReceivedEvent event, String call) {
		sendMsg(event.getChannel(), ":knife: :hand_splayed: :sweat_drops:");
	}
}
